### ISSUE TITLE
CTransaction::GetValueOut() : value out of range 

### ISSUE THREAD

**Issue by mogrith** [sherlockcoin/navajocoin#1]
CTxOut(nValue=116713847.11769971, scriptPubKey=0280ebf83eb1a1a47963da21a2cb994cf1e18d533aa38c280bff1814bf40152da5 OP_CHECKSIG)

---

EXCEPTION: St13runtime_error  
CTransaction::GetValueOut() : value out of range  
D:\Coin Wallets\NAV 2.0.0.0\navajocoin-qt.exe in ThreadStakeMiner()

**Comment by sherlockcoin** [comment]
I believe this issue has been fixed in the newer versions of the client mate , let us know if the problem persists.
